site_name: MetaKG
nav:
- index.md
- Overview of MetaKG.md
- Quick Start.md
- Installation.md
- KG Construction.md
- Query and Search.md
- Biological Analysis.md
- Visualization.md
- Representation Training.md
- MetaKGE.md
- Meta2Vec Embedding.md
- KG Completion.md
- Hypothesis Generation.md
- How to update with LLM.md
- Open Resources.md
theme: readthedocs